version: '3.9'

services:

  backend:
    build:
      context: ./backend

    container_name: crud-backend

    ports:
      - "8081:8080"
    
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend

    container_name: crud-frontend

    ports:
      - "4200:80"

    depends_on:
      - backend
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge