# =====================================================
# MICROSERVIÇO: matricula-service
# =====================================================

# Porta própria ? diferente do monolito (8080)
server.port=8081

# Nome do serviço (útil para identificação em logs)
spring.application.name=matricula-service

# =====================================================
# Banco H2 exclusivo deste microserviço
# Cada microserviço tem seu próprio banco (isolamento)
# =====================================================
spring.datasource.url=jdbc:h2:mem:matriculadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Console H2 acessível em: http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Log SQL para fins didáticos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
